# Keyboard name
CONFIG_ZMK_KEYBOARD_NAME="Udin61"

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Bluetooth TX power boost (max +8 dBm for nRF52840)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Deep sleep after 15 minutes of inactivity (900000 ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
